---
Name: rest_api_oauth
After:
  - 'framework/*'
  - 'cms/*'
  - 'rest_api/*'
---
Injector:
  ApiMemberAuthenticator:
    class: SocialMemberAuthenticator
  SessionValidator:
    class: SessionValidatorWithSocial
FacebookApi:
  AppID: foo_app
  AppSecret: foo_secret
GoogleApi:
  AppID: foo_app
  AppSecret: foo_secret
SessionValidatorWithSocial:
  token_name: Token
  auth_service_name: AuthService
  email_name: Email
  user_id_name: UserID
  password_name: Password