---
Name: rest_api_oauth
After:
  - 'framework/*'
  - 'cms/*'
  - 'rest_api/*'
---
Injector:
  ApiMemberAuthenticator:
    class: SocialMemberAuthenticator
  SessionValidator:
    class: SessionValidatorWithSocial
FacebookApi:
  AppID: foo_app
  AppSecret: foo_secret